### PR TITLE
Add project setup info

### PR DESCRIPTION
**Pull request by moechakucha**

### CODE REVIEW

**Comment by moechakucha** [comment]
oops jitpack failed

**Comment by JieningYu** [comment]
Thank you but I'm going to use Modrinth maven

**Comment by moechakucha** [comment]
> Thank you but I'm going to use Modrinth maven

whats wrong with jitpack its easy to deploy

**Comment by JieningYu** [comment]
fine

**Comment by JieningYu** [comment]
https://jitpack.io/com/github/DM-Earth/DeferredRegistries/0.1/build.log
hmm seems jitpack is using Java8 to build(?

**Pull request merged**
